/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.github.jayzhang.sentmin;



public enum HotelProperties{
  NONE(300),
  SERVICE(301),
  POSITION(302),
  FACILITY(303),
  SANITATION(304),
  PRICE(305),
  BREAKFAST(306),
  OVERALL(307);

  private final int value;

  private HotelProperties(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static HotelProperties findByValue(int value) { 
    switch (value) {
      case 300:
        return NONE;
      case 301:
        return SERVICE;
      case 302:
        return POSITION;
      case 303:
        return FACILITY;
      case 304:
        return SANITATION;
      case 305:
        return PRICE;
      case 306:
        return BREAKFAST;
      case 307:
        return OVERALL;
      default:
        return null;
    }
  }
}
