/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.github.jayzhang.sentmin;



public enum Rates {
  GOOD(200),
  MEDIUM(201),
  BAD(202);

  private final int value;

  private Rates(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Rates findByValue(int value) { 
    switch (value) {
      case 200:
        return GOOD;
      case 201:
        return MEDIUM;
      case 202:
        return BAD;
      default:
        return null;
    }
  }
}
